# Generated by Django 4.1.5 on 2023-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumpost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='name',
        ),
        migrations.AlterField(
            model_name='video',
            name='hosting_method',
            field=models.CharField(choices=[('Y', 'YouTube'), ('S', 'Server')], default='Y', max_length=1),
        ),
    ]
