# Generated by Django 4.1.5 on 2023-03-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumpost',
            options={'ordering': ['-posted_date']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-posted_date']},
        ),
        migrations.AlterModelOptions(
            name='videopost',
            options={'ordering': ['-posted_date']},
        ),
        migrations.RemoveField(
            model_name='albumpost',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='albumpost',
            name='created',
        ),
        migrations.RemoveField(
            model_name='albumpost',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='created',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='object_id',
        ),
    ]
