# Generated by Django 4.1.5 on 2023-03-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_albumpost_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_paths',
            field=models.ManyToManyField(blank=True, to='posts.image'),
        ),
    ]
