# Generated by Django 4.1.5 on 2023-04-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_blogpost_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumpost',
            old_name='image_paths',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='image_paths',
            new_name='images',
        ),
    ]
