# Generated by Django 4.1.5 on 2023-03-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_image_description_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumpost',
            name='post_type',
            field=models.CharField(choices=[('B', 'Blog'), ('A', 'Album'), ('V', 'Video')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('B', 'Blog'), ('A', 'Album'), ('V', 'Video')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='videopost',
            name='post_type',
            field=models.CharField(choices=[('B', 'Blog'), ('A', 'Album'), ('V', 'Video')], default='B', max_length=2),
        ),
    ]
