# Generated by Django 4.1.5 on 2023-03-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_albumpost_post_type_blogpost_post_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video_path',
            field=models.ManyToManyField(to='posts.video'),
        ),
    ]
