# Generated by Django 4.1.5 on 2023-04-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_videopost_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hosting_method',
            field=models.CharField(choices=[('Y', 'YouTube'), ('S', 'Server')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='albumpost',
            name='post_type',
            field=models.CharField(choices=[('B', 'Blog'), ('A', 'Album'), ('V', 'Video')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('B', 'Blog'), ('A', 'Album'), ('V', 'Video')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='post_type',
            field=models.CharField(choices=[('B', 'Blog'), ('A', 'Album'), ('V', 'Video')], default='B', max_length=1),
        ),
    ]
